### ISSUE TITLE
Add more colors to RGB LED component

### ISSUE THREAD

**Issue by SteveDesmond-ca** [ecoAPM/SimpleGPIO#11]
Once PWM is implemented in #7, the RGB LED can show any RGB color!
- add a `TurnColor(Color color)` method
- add some more named colors

**Comment by nightfox0909** [comment]
Id love to take this up if no one is working on it already.

**Comment by stevedesmond-ca** [comment]
:100: go for it!

**Comment by brunocabral88** [comment]
Is this issue still pending implementation? I'd like to work on it if so.

**Comment by stevedesmond-ca** [comment]
Feel free to give it a shot!

**Comment by brunocabral88** [comment]
@stevedesmond-ca, I believe we will indeed have to implement PWM as in issue #7 before we can close this one, since there is no way to set the voltage to values other than 0 or 1. Please correct me if I'm wrong, but the PWM implementation would go in the IPinInterface and its implementations, right?

**Comment by stevedesmond-ca** [comment]
Yeah, I think we need a `PWMManager` or something like that on each pin, to handle the toggle timing, and the pin can then have a `Strength` (better name?) getter/setter that calls into PWM.

My guess is that `sysfs` will be too slow, so you'll need to use the `experimental` flag on the Factory to enable `System.Devices.Gpio` (and therefore the memory mappings) as the backend.

**Comment by SteveDesmond-ca** [comment]
PWM has been implemented as of v2.0.0-beta.2 this afternoon, and I'm planning on adding some helpers/extensions for this over the next week.

**Comment by SteveDesmond-ca** [comment]
As of v2.0.0-beta.3 this afternoon, a new method `RGBLED.SetColor()` can take any `System.Drawing.Color` and adjust software PWM accordingly for each of the RGB pins.

Docs will be updated for v2 final.
