### ISSUE TITLE
Does it support arm?

### ISSUE THREAD

**Issue by INTERNALINTERFERENCE** [ecoAPM/SimpleGPIO#43]
I have this: [EM3566](https://www.cnx-software.com/2021/07/28/boardcon-em3566-linux-sbc-is-powered-by-a-rockchip-rk3566-system-on-module/)

Is it possible to use your library with my controller?

**Comment by SteveDesmond-ca** [comment]
Hi, it looks like that board has an ARMv8 CPU and runs Linux, so .NET should support it!
