### ISSUE TITLE
Can I adapt to BananaPi?

### ISSUE THREAD

**Issue by zhulige** [ecoAPM/SimpleGPIO#47]
https://github.com/BPI-SINOVOIP/RPi.GPIO
https://github.com/BPI-SINOVOIP/BPI-WiringPi2

**Comment by SteveDesmond-ca** [comment]
Hi @zhulige, thanks for the question! According to the Wikipedia page (https://en.m.wikipedia.org/wiki/Banana_Pi), Raspberry Pi and Banana Pi both "use the same 40 pin I/O connector" so I'm happy to say that SimpleGPIO should work out of the box!
